USER_ID = 'jvqrpit5yo8j'
# Your PAT (Personal Access Token) can be found in the portal under Authentification
PAT = 'da6c272af9f345cb8945fcc48d3a9da5'
APP_ID = 'my-first-application-vr48qs'
WORKFLOW_ID = 'workflow-d9626d'
WORKFLOW_ID_TEXT = 'workflow-d9626d'
WORKFLOW_ID_IMAGE = 'workflow-dad285'
WORKFLOW_ID_STORY_GPT3 = 'workflow-4b275c'